# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setItalic(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainSubjectTitle = QtWidgets.QLabel(self.centralwidget)
        self.MainSubjectTitle.setGeometry(QtCore.QRect(340, 130, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.MainSubjectTitle.setFont(font)
        self.MainSubjectTitle.setObjectName("MainSubjectTitle")
        self.MainTitle = QtWidgets.QLabel(self.centralwidget)
        self.MainTitle.setGeometry(QtCore.QRect(240, 0, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.MainTitle.setFont(font)
        self.MainTitle.setObjectName("MainTitle")
        self.MainSubject_ComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.MainSubject_ComboBox.setGeometry(QtCore.QRect(350, 170, 111, 26))
        self.MainSubject_ComboBox.setObjectName("MainSubject_ComboBox")
        self.MainSubject_ComboBox.addItem("")
        self.MainSubject_ComboBox.setItemText(0, "")
        self.MainSubject_ComboBox.addItem("")
        self.MainSubject_ComboBox.addItem("")
        self.MainSubject_ComboBox.addItem("")
        self.MainSubject_ComboBox.addItem("")
        self.MainSubject_ComboBox.addItem("")
        self.MainSubject_ComboBox.addItem("")
        self.MainSubject_ComboBox.addItem("")
        self.MainSubject_ComboBox.addItem("")
        self.MainSubject_ComboBox.addItem("")
        self.MainSubject_ComboBox.addItem("")
        self.MainSubject_ComboBox.addItem("")
        self.MainSubject_ComboBox.addItem("")
        self.MainSubject_ComboBox.setItemText(12, "")
        self.checkbox_one = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_one.setGeometry(QtCore.QRect(270, 170, 61, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.checkbox_one.setFont(font)
        self.checkbox_one.setObjectName("checkbox_one")
        self.MainTopicTitle = QtWidgets.QLabel(self.centralwidget)
        self.MainTopicTitle.setGeometry(QtCore.QRect(360, 220, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.MainTopicTitle.setFont(font)
        self.MainTopicTitle.setObjectName("MainTopicTitle")
        self.MainTopic_editbox = QtWidgets.QLineEdit(self.centralwidget)
        self.MainTopic_editbox.setGeometry(QtCore.QRect(350, 250, 113, 21))
        self.MainTopic_editbox.setObjectName("MainTopic_editbox")
        self.FocusPoints_title = QtWidgets.QLabel(self.centralwidget)
        self.FocusPoints_title.setGeometry(QtCore.QRect(350, 300, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.FocusPoints_title.setFont(font)
        self.FocusPoints_title.setObjectName("FocusPoints_title")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(350, 330, 111, 79))
        self.textEdit.setObjectName("textEdit")
        self.checkbox_two = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_two.setGeometry(QtCore.QRect(270, 250, 61, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.checkbox_two.setFont(font)
        self.checkbox_two.setObjectName("checkbox_two")
        self.checkbox_three = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_three.setGeometry(QtCore.QRect(270, 330, 61, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.checkbox_three.setFont(font)
        self.checkbox_three.setObjectName("checkbox_three")
        self.CancelOk_button = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.CancelOk_button.setGeometry(QtCore.QRect(330, 450, 164, 32))
        self.CancelOk_button.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.CancelOk_button.setObjectName("CancelOk_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 80, 211, 20))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuForm = QtWidgets.QMenu(self.menubar)
        self.menuForm.setObjectName("menuForm")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.newfile_action = QtWidgets.QAction(MainWindow)
        self.newfile_action.setObjectName("newfile_action")
        self.savefile_action = QtWidgets.QAction(MainWindow)
        self.savefile_action.setObjectName("savefile_action")
        self.saveAsFile_action = QtWidgets.QAction(MainWindow)
        self.saveAsFile_action.setObjectName("saveAsFile_action")
        self.recentFile = QtWidgets.QAction(MainWindow)
        self.recentFile.setText("")
        self.recentFile.setObjectName("recentFile")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.Undo_action = QtWidgets.QAction(MainWindow)
        self.Undo_action.setObjectName("Undo_action")
        self.cut_action = QtWidgets.QAction(MainWindow)
        self.cut_action.setObjectName("cut_action")
        self.paste_action = QtWidgets.QAction(MainWindow)
        self.paste_action.setObjectName("paste_action")
        self.actionLayout_Preview = QtWidgets.QAction(MainWindow)
        self.actionLayout_Preview.setObjectName("actionLayout_Preview")
        self.openfile_action = QtWidgets.QAction(MainWindow)
        self.openfile_action.setObjectName("openfile_action")
        self.menuFile.addAction(self.newfile_action)
        self.menuFile.addAction(self.openfile_action)
        self.menuFile.addAction(self.savefile_action)
        self.menuFile.addAction(self.saveAsFile_action)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.Undo_action)
        self.menuEdit.addAction(self.cut_action)
        self.menuEdit.addAction(self.paste_action)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuForm.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MainSubjectTitle.setText(_translate("MainWindow", "  Main Subject"))
        self.MainTitle.setText(_translate("MainWindow", "Welcome to EassayWritter!"))
        self.MainSubject_ComboBox.setItemText(1, _translate("MainWindow", "History "))
        self.MainSubject_ComboBox.setItemText(2, _translate("MainWindow", "Civics and Goverment"))
        self.MainSubject_ComboBox.setItemText(3, _translate("MainWindow", "Humanities"))
        self.MainSubject_ComboBox.setItemText(4, _translate("MainWindow", "Economics"))
        self.MainSubject_ComboBox.setItemText(5, _translate("MainWindow", "English"))
        self.MainSubject_ComboBox.setItemText(6, _translate("MainWindow", "Reading/Language Arts"))
        self.MainSubject_ComboBox.setItemText(7, _translate("MainWindow", "World Languages "))
        self.MainSubject_ComboBox.setItemText(8, _translate("MainWindow", "Mathematics"))
        self.MainSubject_ComboBox.setItemText(9, _translate("MainWindow", "Biology"))
        self.MainSubject_ComboBox.setItemText(10, _translate("MainWindow", "Chemistry "))
        self.MainSubject_ComboBox.setItemText(11, _translate("MainWindow", "Other"))
        self.checkbox_one.setText(_translate("MainWindow", "Step 1"))
        self.MainTopicTitle.setText(_translate("MainWindow", "Main Topic "))
        self.FocusPoints_title.setText(_translate("MainWindow", "Focus Points"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.checkbox_two.setText(_translate("MainWindow", "Step 2"))
        self.checkbox_three.setText(_translate("MainWindow", "Step 3"))
        self.label.setText(_translate("MainWindow", "Create your essay in 3 essay steps"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuForm.setTitle(_translate("MainWindow", "Form"))
        self.newfile_action.setText(_translate("MainWindow", "New"))
        self.newfile_action.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.savefile_action.setText(_translate("MainWindow", "Save "))
        self.savefile_action.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.saveAsFile_action.setText(_translate("MainWindow", "Save as.."))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.Undo_action.setText(_translate("MainWindow", "Undo"))
        self.Undo_action.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.cut_action.setText(_translate("MainWindow", "Cut"))
        self.cut_action.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.paste_action.setText(_translate("MainWindow", "Paste"))
        self.paste_action.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionLayout_Preview.setText(_translate("MainWindow", "Layout Preview"))
        self.openfile_action.setText(_translate("MainWindow", "Open"))
        self.openfile_action.setShortcut(_translate("MainWindow", "Ctrl+O"))
